SELECT 
    MAX(p.AMOUNT) AS SALARY, 
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS NAME, 
    TIMESTAMPDIFF(YEAR, e.DOB, CURDATE()) AS AGE, 
    d.DEPARTMENT_NAME 

FROM PAYMENTS p 

JOIN EMPLOYEE e ON p.EMP_ID = e.EMP_ID 

JOIN DEPARTMENT d ON e.DEPARTMENT = d.DEPARTMENT_ID 

WHERE DAY(p.PAYMENT_TIME) != 1 

GROUP BY e.EMP_ID, e.FIRST_NAME, e.LAST_NAME, e.DOB, d.DEPARTMENT_NAME 

ORDER BY SALARY DESC 

LIMIT 1;
